### ISSUE TITLE
link linepay url

### ISSUE THREAD

**Issue by hua547878** [line/flutter_line_sdk#38]
I use a linepay request API and get a linepay app url, but I don't know how to use it with deep link and app link, will you develop the feature of link linepay url in this package?

linepay app url seems like:"line://pay/payment/xxxxxxxx"

**Comment by onevcat** [comment]
Umm. I guess this is not a topic related to LINE SDK.

I am not an expert of Flutter, but I guess if you want to open such a URL with certain scheme, you can try the Flutter official [url_launcher](https://pub.dev/packages/url_launcher) package, which is exactly for that purpose.

I am closing it since this is an off-topic in this repo. If you have any other concerns about LINE SDK, please feel free to open a new issue.

Best regards.
