### ISSUE TITLE
How can I get line_id of my account when I logged in with Line Login?

### ISSUE THREAD

**Issue by nguyenvanan18031993** [line/flutter_line_sdk#64]
Thanks so much for your awesome SDK. I'm using this SDK to log in with my Line app. After that I need to find my Line_id which can help me save that which can help the manager open the Line app which has that profile to add friends.

**Comment by onevcat** [comment]
Hi,

Sorry for the late reply.

As a third-party user, you cannot get the actual LINE ID of the user which being used in LINE app itself. As a private communication app, LINE cannot share that user actual ID to your apps. Otherwise, the third-party app can construct a relationship of users without proper agreement (moreover, it is definitely user privacy and with legal issues).

Instead, LINE SDK would return you back with an encrypted user ID just for your app / channel. It is guaranteed to be the same for the same channel, but be different for different channels (and LINE app). This ID can be retrieved in the result after login (mentioned [here](https://github.com/line/flutter_line_sdk/#login)).
